# -- coding:utf-8 --
import sys
sys.path.append("../acgweb")

import json
from acgweb.controller.notify import *

data = {
    NOTIFY_ACTIVITY_APPOINT       : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 1},
    NOTIFY_ACTIVITY_MODIFY        : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_ACTIVITY_CANCEL        : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_APPROVE_APPLY          : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 1},
    NOTIFY_DECLINE_APPLY          : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 1},
    NOTIFY_COVER_DUTY             : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 1},
    NOTIFY_ACTIVITY_NEARLY_BEGIN  : { NOTIFY_MESSAGE: 0, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 1},
    NOTIFY_ACTIVITY_MARK_ENDTIME  : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_DECLINE_DUTY           : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_SPIDER                 : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 0, NOTIFY_SMS: 0},
    NOTIFY_TODO                   : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_ERROR                  : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0},
    NOTIFY_OTHER                  : { NOTIFY_MESSAGE: 1, NOTIFY_EMAIL: 1, NOTIFY_APP: 1, NOTIFY_SMS: 0}
}

print json.dumps(data)
